### ISSUE TITLE
Remove all old queue commits

### ISSUE THREAD

**Issue by josecelano** [Nautilus-Cyberneering/chinese-ideographs-website#48]
Relates to: https://github.com/Nautilus-Cyberneering/library-consumer/issues/28

We cannot use the new Git-Queue version with the old queue commits because there are some breaking changes (the queue name is validated and some commit subjects contain the job id).

For now, we are going to fix it by removing all the old queue commits.

**Comment by josecelano** [comment]
Old queue commits deleted with [reposurgeon](http://www.catb.org/~esr/reposurgeon/).

The reposurgeon script:

```s
$ cat remove-queue-commits-website.rs 
# Load the project into main memory
# Warning: this command is slow because Subversion is slow.
read ./chinese-ideographs-website

# Check for and report glitches such as timestamp collisions,
# ill-formed committer/author IDs, multiple roots, etc.
lint

# Commit deletion
/📝/c delete
/CLAIM LOCK/c delete
/RELEASE LOCK/c delete

# We want to write a Git repository
prefer git

# Do it
rebuild chinese-ideographs-website-without-queue-commits
```

How to execute the script:

```s
reposurgeon "script remove-queue-commits-website.rs"
```

**Comment by josecelano** [comment]
One of the disadvantages of this solution is we lose the GPG signature for all commits :-(.

**Comment by da2ce7** [comment]
@josecelano Yup. Any tool that reworks the commit-history will destroy the gpg signatures. Unfortunately this is unavoidable until we use diff-based version control system, such as Pijul.
